# Generated by Django 5.2.12 on 2026-03-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('rating', models.CharField(blank=True, help_text='Movie age rating, e.g. G, PG-13, 14, 18', max_length=10)),
                ('poster_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Defines whether the movie is currently available in the catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_rows', models.PositiveIntegerField(default=10)),
                ('total_columns', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('language', models.CharField(choices=[('SUB', 'Subtitled'), ('DUB', 'Dubbed')], default='SUB', max_length=10)),
                ('format_type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Defines whether this session can still be listed or sold.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movies.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='movies.room')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['start_time'],
            },
        ),
    ]
